server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-test-server      #匹配后提供服务的路由地址
          predicates:
            - Path=/test/get   # 断言，路径相匹配的进行路由

    nacos:
      discovery:
        server-addr: localhost:8848
